name: webinar
description: webinar project.

publish_to: 'none'


version: 11.0.0+11

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  change_app_package_name:
  flutter_svg:
  provider:
  audio_session: ^0.1.21
  dio:
  persian_number_utility:
#  file_picker: ^5.2.5
  shared_preferences:
  flutter_native_splash:
  loading_indicator:
  get_it:
  flutter_advanced_drawer:
  flutter_rating_bar:
  google_sign_in: ^6.3.0
  http:
  flutter_widget_from_html:
#  video_player: ^2.9.5
  share_plus: ^11.0.0
  chewie:
  permission_handler:
  path_provider:
  open_file:
  flutter_image_compress: ^2.4.0
  image_picker:
  flutter_slidable:
  webview_flutter: ^4.4.2
  pod_player: ^0.2.2
  flutter_tts:
  local_auth:
  table_calendar:
  confetti:
  animated_flip_counter:
  syncfusion_flutter_pdfviewer:
  timezone:
  in_app_purchase:
  sign_in_with_apple:
  vector_math: ^2.2.0
  flutter_inappwebview:
  lottie:
  shimmer:
  firebase_messaging: ^15.2.5
  flutter_local_notifications:
  hive:
  hive_flutter:
  connectivity_plus: ^6.1.4
  cached_network_image:
  flutter_html:
  fl_chart:

dependency_overrides:
  vector_math: ^2.2.0
  flutter_widget_from_html_core: ^0.16.0
  flutter_widget_from_html: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9


flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#00BA63"
  color_dark: "#00BA63"

flutter:
  generate: true

  uses-material-design: true


  assets:
    - assets/image/jpg/
    - assets/image/flags/
    - assets/image/png/
    - assets/image/svg/
    - assets/image/json/


  fonts:
    - family: SF-Pro-Bold
      fonts:
        - asset: assets/font/sf-pro-bold.otf
    - family: SF-Pro-Regular
      fonts:
        - asset: assets/font/sf-pro-regular.otf
    
    - family: Vazir-Bold
      fonts:
        - asset: assets/font/vazir-bold.ttf
    - family: Vazir-Regular
      fonts:
        - asset: assets/font/vazir-regular.ttf

    

